import type { ChildProcessWithoutNullStreams } from 'node:child_process';
import { execSync, spawn } from 'node:child_process';
import { chmodSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test as baseTest } from 'vitest';

export interface WranglerDevOptions {
  cwd?: string;
  timeout?: number;
  env?: typeof process.env;
}

/**
 * Wrangler hardcodes `--platform linux/amd64` for all docker pulls and builds
 * (see wrangler's containers-shared/src/images.ts and build.ts). On arm64
 * hosts (e.g. Apple Silicon Macs) this forces the cloudflare/proxy-everything
 * egress interceptor to run under emulation, where it crashes with
 * `setsockoptint: protocol not available` and brings the whole container down.
 *
 * To make `WranglerDevRunner` "just work" on arm64 hosts, we transparently
 * shim `docker` with a wrapper script that rewrites `linux/amd64` ->
 * `linux/arm64` before invoking the real docker binary, and point wrangler
 * at it via WRANGLER_DOCKER_BIN.
 *
 * Returns the wrapper paths (so callers can clean up the temp dir), or
 * undefined if no shim is needed -- i.e. host is amd64, host is some other
 * arch we have no story for, or WRANGLER_DOCKER_BIN is already set.
 */
function maybeCreateDockerPlatformShim(
  env: typeof process.env
): { wrapperDir: string; wrapperPath: string } | undefined {
  if (env.WRANGLER_DOCKER_BIN) return undefined;
  if (process.arch !== 'arm64') return undefined;

  // Find the real docker binary.
  let realDocker: string;
  try {
    realDocker = execSync('command -v docker', { encoding: 'utf8' }).trim();
  } catch {
    // No docker on PATH; let wrangler produce its own error.
    return undefined;
  }
  if (!realDocker) return undefined;

  const wrapperDir = mkdtempSync(join(tmpdir(), 'cf-containers-docker-shim-'));
  const wrapperPath = join(wrapperDir, 'docker');
  // POSIX-sh script that walks the original argv exactly once, replacing
  // any "linux/amd64" tokens with "linux/arm64". The trailing exec hands
  // the rewritten argv to the real docker binary.
  const script = `#!/bin/sh
# Auto-generated by @cloudflare/containers WranglerDevRunner.
# Rewrites --platform linux/amd64 -> linux/arm64 so wrangler's hardcoded
# amd64 pulls/builds work on this arm64 host without emulation.
n=$#
i=0
while [ $i -lt $n ]; do
  a=$1
  shift
  if [ "$a" = "linux/amd64" ]; then
    set -- "$@" "linux/arm64"
  else
    set -- "$@" "$a"
  fi
  i=$((i + 1))
done
exec ${JSON.stringify(realDocker)} "$@"
`;
  writeFileSync(wrapperPath, script);
  chmodSync(wrapperPath, 0o755);
  return { wrapperDir, wrapperPath };
}

export class WranglerDevRunner {
  private process: ChildProcessWithoutNullStreams;
  private stdout: string = '';
  private stderr: string = '';
  private url: string | null = null;
  private readonly timeout: number;
  private urlPromise: Promise<string>;
  private dockerShim?: { wrapperDir: string; wrapperPath: string };
  private destroyed = false;

  constructor(private options: WranglerDevOptions = {}) {
    this.timeout = options.timeout || 30000;

    const baseEnv = { ...(this.options.env || process.env) };
    this.dockerShim = maybeCreateDockerPlatformShim(baseEnv);
    if (this.dockerShim) {
      baseEnv.WRANGLER_DOCKER_BIN = this.dockerShim.wrapperPath;
    }

    this.process = spawn('npx', ['wrangler', 'dev'], {
      cwd: this.options.cwd,
      env: baseEnv,
      stdio: 'pipe',
      // Put wrangler (and the workerd grandchildren it spawns) in their own
      // process group so we can clean up the whole tree on destroy.
      detached: true,
    });

    this.urlPromise = new Promise((resolve, reject) => {
      const timeoutId = setTimeout(() => {
        reject(new Error(`Timeout after ${this.timeout}ms waiting for wrangler dev to be ready`));
      }, this.timeout);

      this.process.stdout.on('data', (data: Buffer) => {
        const output = data.toString();
        this.stdout += output;
        console.log(output);

        // Check for ready pattern
        const match = output.match(/Ready on (?<url>https?:\/\/.*)/);
        if (match && match.groups?.url && !this.url) {
          this.url = match.groups.url;
          clearTimeout(timeoutId);
          resolve(this.url);
        }
      });

      this.process.stderr.on('data', (data: Buffer) => {
        this.stderr += data.toString();
        console.log(data.toString());
      });
    });

    // Best-effort: if the parent vitest process exits unexpectedly (Ctrl-C,
    // an unhandled rejection killing the runner, etc.) still try to clean up
    // the wrangler/workerd tree. These handlers are no-ops once destroy()
    // has run.
    const cleanupOnExit = () => {
      this.killProcessGroup('SIGKILL');
      this.cleanupShim();
    };
    process.once('exit', cleanupOnExit);
  }

  getStdout(): string {
    return this.stdout;
  }

  getStderr(): string {
    return this.stderr;
  }

  async getUrl(): Promise<string> {
    return this.urlPromise;
  }

  private killProcessGroup(signal: NodeJS.Signals): void {
    const pid = this.process.pid;
    if (pid === undefined) return;
    try {
      // Negative PID -> signal the entire process group, which catches
      // npx -> wrangler -> workerd descendants spawned by `detached: true`.
      process.kill(-pid, signal);
    } catch (err: unknown) {
      // ESRCH means the group is already gone; anything else we log but
      // don't throw because destroy() is best-effort.
      const code = (err as NodeJS.ErrnoException)?.code;
      if (code !== 'ESRCH') {
        console.warn(`Failed to kill wrangler process group ${pid} with ${signal}:`, err);
      }
    }
  }

  private cleanupShim(): void {
    if (!this.dockerShim) return;
    try {
      rmSync(this.dockerShim.wrapperDir, { recursive: true, force: true });
    } catch {
      // ignore
    }
    this.dockerShim = undefined;
  }

  async destroy(containerId?: string[]): Promise<void> {
    if (this.destroyed) return;
    this.destroyed = true;

    for (const id of containerId ?? []) {
      try {
        await fetch(this.url + '/destroy?id=' + id);
      } catch {
        // The wrangler process may already be gone; ignore.
      }
    }
    // give it a second to run the onStop hook before we kill the process
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Send SIGTERM to the whole group, then escalate to SIGKILL if anything
    // is still hanging on (workerd is a notable repeat offender).
    this.killProcessGroup('SIGTERM');

    await new Promise<void>(resolve => {
      let settled = false;
      const done = () => {
        if (settled) return;
        settled = true;
        resolve();
      };
      this.process.on('close', done);
      // Fallback: if SIGTERM didn't take, escalate.
      setTimeout(() => {
        this.killProcessGroup('SIGKILL');
        // Give the OS a moment to reap.
        setTimeout(done, 250);
      }, 2000);
    });

    this.cleanupShim();
  }
}

/**
 * Vitest test fixture that provisions a `WranglerDevRunner` and tears it
 * down (and any workerd grandchildren / temp docker shim) automatically
 * after the test resolves, regardless of pass/fail.
 *
 * Use it via the `test` re-export from this module instead of importing
 * `test` from `vitest` directly:
 *
 *   import { test } from '../../test-helpers';
 *   test('my test', async ({ runner }) => {
 *     const url = await runner.getUrl();
 *     // ...
 *   });
 *
 * Tests that need to issue the in-worker `/destroy?id=<id>` fetch before
 * shutdown (e.g. to exercise the container's `onStop` hook) can still call
 * `runner.destroy([id])` explicitly; the fixture cleanup is idempotent and
 * will no-op on the second call.
 */
export const test = baseTest.extend<{ runner: WranglerDevRunner }>({
  runner: async ({}, use) => {
    const runner = new WranglerDevRunner();
    try {
      await use(runner);
    } finally {
      await runner.destroy();
    }
  },
});

export const fetchWithAccess = async (url: string, options: RequestInit = {}) => {
  const accessClientId = process.env.ACCESS_CLIENT_ID;
  const accessClientSecret = process.env.ACCESS_SECRET;

  if (!accessClientId || !accessClientSecret) {
    throw new Error(
      'CF-Access-Client-Id and CF-Access-Client-Secret must be set in environment variables'
    );
  }

  const headers = new Headers(options.headers || {});
  headers.set('CF-Access-Client-Id', accessClientId);
  headers.set('CF-Access-Client-Secret', accessClientSecret);

  return await fetch(url, {
    ...options,
    headers,
  });
};
